apiVersion: v1
kind: Service
metadata:
  name: encrypstego
spec:
  selector:
    app: encrypstego
  ports:
    - protocol: TCP
      port: 1324
      targetPort: 1324

---

apiVersion: v1
kind: Service
metadata:
  name: crypstego
spec:
  type: NodePort
  selector:
    app: crypstego
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323
      nodePort: 30007

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypstego
  labels:
    app: encrypstego
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encrypstego
  template:
    metadata:
      labels:
        app: encrypstego
    spec:
      containers:
      - name: encrypstego
        image: rixelanya/crypstego:encr-0.0.2
        ports:
        - containerPort: 1324

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypstego
  labels:
    app: crypstego
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypstego
  template:
    metadata:
      labels:
        app: crypstego
    spec:
      containers:
      - name: crypstego
        image: rixelanya/crypstego:stego-kube-0.0.2
        ports:
        - containerPort: 1323
