apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypstegohelm.fullname" . }}-crypstego
  labels:
  {{- include "crypstegohelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.crypstego.type }}
  selector:
    app: crypstego
  {{- include "crypstegohelm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.crypstego.ports | toYaml | nindent 2 -}}